### ISSUE TITLE
Statepoint in Part 3

### ISSUE THREAD

**Issue by tjlaboss** [mit-crpg/openmc-workshop#1]
There seems to be a problem with the statepoint file in the [Part 3](https://github.com/mit-crpg/openmc-workshop/blob/master/Part3/Part3-Solutions.ipynb) iPython notebook.

I'm getting an error and seeing a weird traceback when running cell `[2]:` in the notebook,
`sp = openmc.StatePoint('statepoint.100.h5')`; see ~~attached~~ the post below. I get pretty much the same error trying to load the statepoint outside of the notebook, too.

Loading `"statepoint.50.h5"` generated in Part 2 works just fine, which leads me to believe that the `"statepoint.100.h5"` was made with an obsolete version of HDF5.

Edit: This goes for the "summary.h5" file, as well.

**Comment by tjlaboss** [comment]
```python

KeyError                                  Traceback (most recent call last)
<ipython-input-6-06138ecf01df> in <module>()
----> 1 sp = openmc.StatePoint('statepoint.100.h5')

/home/travis/.miniconda3/lib/python3.5/openmc/statepoint.py in __init__(self, filename, autolink)
    139             path_summary = os.path.join(os.path.dirname(filename), 'summary.h5')
    140             if os.path.exists(path_summary):
--> 141                 su = openmc.Summary(path_summary)
    142                 self.link_with_summary(su)
    143 

/home/travis/.miniconda3/lib/python3.5/openmc/summary.py in __init__(self, filename)
     36 
     37         self._read_metadata()
---> 38         self._read_nuclides()
     39         self._read_geometry()
     40         self._read_tallies()

/home/travis/.miniconda3/lib/python3.5/openmc/summary.py in _read_nuclides(self)
     73     def _read_nuclides(self):
     74         self.nuclides = {}
---> 75         n_nuclides = self._f['nuclides/n_nuclides_total'].value
     76         names = self._f['nuclides/names'].value
     77         awrs = self._f['nuclides/awrs'].value

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1486401638188/work/h5py/_objects.c:2856)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1486401638188/work/h5py/_objects.c:2814)()

/home/travis/.miniconda3/lib/python3.5/site-packages/h5py/_hl/group.py in __getitem__(self, name)
    164                 raise ValueError("Invalid HDF5 object reference")
    165         else:
--> 166             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    167 
    168         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1486401638188/work/h5py/_objects.c:2856)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1486401638188/work/h5py/_objects.c:2814)()

h5py/h5o.pyx in h5py.h5o.open (/home/ilan/minonda/conda-bld/h5py_1486401638188/work/h5py/h5o.c:3742)()

KeyError: 'Unable to open object (Component not found)'
```

**Comment by wbinventor** [comment]
The state points likely need to be generated with whatever version of
OpenMC you have installed on your system.

**Comment by tjlaboss** [comment]
Good to know. It looks like the notebooks from Physor were using v 0.7.1.

@smharper : let's make sure we get a fresh statepoint/summary using the version we'll be running on AWS

**Comment by wbinventor** [comment]
@tjlaboss glad you solved the issue. For future reference, you should note that we have a revision system for statepoint files as discussed here:

http://openmc.readthedocs.io/en/latest/io_formats/statepoint.html?highlight=statepoint%20version

The current "develop" branch is on statepoint version 15. Every time the contents or formatting of the statepoint files change, the revision number is incremented. You can check the number on a statepoint HDF5 file via the "revision" dataset. Likewise, the `openmc.StatePoint` Python class is specifically designed to be compatible with a single revision number, as you can see here:

https://github.com/mit-crpg/openmc/blob/develop/openmc/statepoint.py#L123

A few useful tidbits of information that may come in handy as you resolve these issues in the future!

**Comment by smharper** [comment]
This is now fixed on the "irsn" branch.  I'll close this issue when I move that fix over to master.
